pipeline {
    agent any

    stages {
        stage('Clonar Código') {
            steps {
                checkout scm
            }
        }

        stage('Instalar Dependencias') {
            steps {
                sh 'pip install -r Jenkins/requirements.txt'
            }
        }

        stage('Entrenar Modelo') {
            steps {
                sh 'python Jenkins/train.py'
            }
        }

        stage('Ejecutar Pruebas') {
            steps {
                sh 'pytest Jenkins/test.py'
            }
        }
    }
}

