pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo "Paso 1: Clonando el repositorio..."
                checkout scm
                echo "Repositorios clonados exitosamente."
            }
        }
        
        stage('Verificar Python y Pip') {
            steps {
                echo "Paso 2: Verificando la instalación de Python y Pip..."
                script {
                    try {
                        sh 'python --version'
                        sh 'pip --version'
                        echo "Python y pip están instalados correctamente."
                    } catch (Exception e) {
                        echo "Error al verificar Python o Pip. Revisa la configuración del entorno."
                        throw e  // Esto detendrá el pipeline si falla la verificación
                    }
                }
            }
        }

        stage('Instalar Dependencias') {
            steps {
                echo "Paso 3: Instalando dependencias desde requirements.txt..."
                script {
                    try {
                        sh 'pip install -r Jenkins/requirements.txt'
                        echo "Dependencias instaladas correctamente."
                    } catch (Exception e) {
                        echo "Error al instalar dependencias. Verifica el archivo requirements.txt."
                        throw e  // Detiene el pipeline si falla la instalación
                    }
                }
            }
        }

        stage('Entrenar Modelo') {
            steps {
                echo "Paso 4: Entrenando el modelo..."
                script {
                    try {
                        sh 'python Jenkins/train.py'
                        echo "Modelo entrenado exitosamente."
                    } catch (Exception e) {
                        echo "Error al entrenar el modelo. Revisa el script train.py."
                        throw e  // Detiene el pipeline si hay un error
                    }
                }
            }
        }

        stage('Ejecutar Pruebas') {
            steps {
                echo "Paso 5: Ejecutando las pruebas..."
                script {
                    try {
                        sh 'python Jenkins/test.py'
                        echo "Pruebas ejecutadas correctamente."
                    } catch (Exception e) {
                        echo "Error al ejecutar las pruebas. Revisa el script test.py."
                        throw e  // Detiene el pipeline si hay un error
                    }
                }
            }
        }

    }

    post {
        always {
            echo "El pipeline ha terminado."
        }
        success {
            echo "El pipeline se ejecutó correctamente sin errores."
        }
        failure {
            echo "El pipeline ha fallado. Revisa los logs para más detalles."
        }
    }
}






