pipeline {
    agent any

    environment {
        // Aseguramos que python y pip estén disponibles
        PYTHON = 'python'
        PIP = 'pip'
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Clonando el repositorio...'
                checkout scm
            }
        }

        stage('Instalar Dependencias') {
            steps {
                echo 'Verificando instalación de Python y pip'
                script {
                    // Verificar Python y pip
                    sh '''
                        $PYTHON --version
                        $PIP --version
                        $PIP install -r Jenkins/requirements.txt
                    '''
                }
            }
        }

        stage('Entrenar Modelo') {
            steps {
                echo 'Entrenando el modelo...'
                script {
                    // Aseguramos que train.py está en la carpeta Jenkins
                    sh """
                        $PYTHON Jenkins/train.py
                    """
                }
            }
        }

        stage('Ejecutar Pruebas') {
            steps {
                echo 'Ejecutando pruebas...'
                script {
                    // Aseguramos que test.py está en la carpeta Jenkins
                    sh """
                        $PYTHON Jenkins/test.py
                    """
                }
            }
        }
    }

    post {
        always {
            echo 'El pipeline ha terminado.'
        }
    }
}





